[package]
name = "contracts"
version = "0.2.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.8.2"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.20.0" }

[cairo]
# sierra-replace-ids = false  # Not needed without Garaga

[dev-dependencies]
snforge_std = "0.50.0"

[[target.starknet-contract]]
casm = true # taggle this to `false` to speed up compilation/script tests

[tool.fmt]
sort-module-level-items = true

[[tool.snforge.fork]]
name = "SEPOLIA_LATEST"
url = "https://starknet-sepolia.g.alchemy.com/starknet/version/rpc/v0_10/oX6CVMWKcDva93Z4ZrmZ1"
block_id.tag = "latest"

[tool]
panic-backtrace = true

